spring:
  application:
    name: history
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: 12345
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    ## 선택적 hikari
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 600000

server:
  port: 8080

#Mybatis 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.delivery.history.api.model
